
name: Build Deb Package

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:
  release:
    types: ["published"]
jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: chmod 755 homeassistant-supervised/DEBIAN/p*
      - run: dpkg-deb --build --root-owner-group homeassistant-supervised